# Generated by Django 6.0.7 on 2026-07-31 03:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_sms_derived',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#16a085', max_length=20, verbose_name='কালার কোড'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fas fa-utensils', 'Food / Mess Meal'), ('fas fa-coffee', 'Tea & Snacks / Cafeteria'), ('fas fa-shopping-basket', 'Groceries / Bazar'), ('fas fa-book', 'Books & Study Materials'), ('fas fa-graduation-cap', 'Tuition Fee'), ('fas fa-print', 'Printing & Stationery'), ('fas fa-bus', 'Local Bus / Transport'), ('fas fa-motorcycle', 'Rickshaw / CNG Fare'), ('fas fa-plane', 'Tour & Traveling'), ('fas fa-home', 'Mess Rent / House Rent'), ('fas fa-bolt', 'Electricity Bill'), ('fas fa-wifi', 'Internet & Wi-Fi'), ('fas fa-mobile-alt', 'Mobile Recharge'), ('fas fa-tshirt', 'Clothing / Shopping'), ('fas fa-medkit', 'Medical / Pharmacy'), ('fas fa-film', 'Entertainment & Movies'), ('fas fa-gift', 'Gifts & Daan'), ('fas fa-futbol', 'Sports & Gym'), ('fas fa-wallet', 'Pocket Money / Salary'), ('fas fa-university', 'Scholarship / Bank')], default='fas fa-utensils', max_length=50, verbose_name='আইকন'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False, verbose_name='আয় ক্যাটাগরি কি?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'আয়'), ('expense', 'খরচ')], default='expense', max_length=10, verbose_name='ধরণ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ক্যাটাগরির নাম'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ (টাকা)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category', verbose_name='ক্যাটাগরি'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='নোট বা বিবরণ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='শিরোনাম'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
