# Generated by Django 6.0 on 2026-07-31 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transaction_options_remove_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False, verbose_name='আয় ক্যাটাগরি কি?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category', verbose_name='ক্যাটাগরির'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'আয়'), ('expense', 'খরচ')], default='expense', max_length=10, verbose_name='ধরণ'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='বাজেটের পরিমাণ (টাকা)')),
                ('month', models.IntegerField(verbose_name='মাস')),
                ('year', models.IntegerField(verbose_name='বছর')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category', verbose_name='ক্যাটাগরি')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'বাজেট',
                'verbose_name_plural': 'বাজেটসমূহ',
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
