# Generated by Django 6.0 on 2026-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_category_is_income_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='শিরোনাম'),
        ),
    ]
