# Generated by Django 6.0 on 2026-08-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_transaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fas fa-utensils', 'Food & Snacks'), ('fas fa-bus', 'Transport & Commute'), ('fas fa-home', 'Rent & Mess Bill'), ('fas fa-bolt', 'Utilities (Gas/Electricity)'), ('fas fa-wifi', 'Internet & Mobile'), ('fas fa-book', 'Study & Stationery'), ('fas fa-graduation-cap', 'University Fee'), ('fas fa-chalkboard-teacher', 'Tuition & Coaching'), ('fas fa-shopping-bag', 'Shopping'), ('fas fa-cut', 'Hair Cut & Grooming'), ('fas fa-medkit', 'Health & Medical'), ('fas fa-gift', 'Gifts & Donation'), ('fas fa-coffee', 'Tea & Coffee'), ('fas fa-tshirt', 'Laundry & Iron'), ('fas fa-film', 'Entertainment & Movies'), ('fas fa-plane', 'Tour & Travel'), ('fas fa-wallet', 'bKash / Nagad Cashout'), ('fas fa-hand-holding-usd', 'Debt Repayment'), ('fas fa-piggy-bank', 'Savings & Deposit'), ('fas fa-shield-alt', 'Emergency Fund'), ('fas fa-ellipsis-h', 'Other Expenses'), ('fas fa-laptop-code', 'Freelancing'), ('fas fa-briefcase', 'Job Salary'), ('fas fa-award', 'Scholarship'), ('fas fa-book-reader', 'Tuition Income'), ('fas fa-coins', 'Pocket Money'), ('fas fa-store', 'Business Income'), ('fas fa-shopping-cart', 'Online Sales'), ('fas fa-chart-line', 'Investment'), ('fas fa-hand-holding-heart', 'Dividend / Profit'), ('fas fa-undo-alt', 'Money Back / Return'), ('fas fa-plus-circle', 'Other Income')], default='fas fa-utensils', max_length=50, verbose_name='আইকন'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False, verbose_name='আয় ক্যাটাগরি কি? (True হলে ইনকাম, False হলে খরচ)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category', verbose_name='ক্যাটাগরি'),
        ),
    ]
