# Generated by Django 6.0 on 2026-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_category_icon_alter_category_is_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Tuition & Fees', 'Tuition & Fees'), ('Books & Notes', 'Books & Notes'), ('Stationery', 'Stationery'), ('Courses & Training', 'Courses & Training'), ('Mess / Hall Bill', 'Mess / Hall Bill'), ('Restaurants & Fast Food', 'Restaurants & Fast Food'), ('Tea & Snacks', 'Tea & Snacks'), ('Groceries', 'Groceries'), ('Bus / Local Transport', 'Bus / Local Transport'), ('Rickshaw & CNG', 'Rickshaw & CNG'), ('Bike Fuel / Maintenance', 'Bike Fuel / Maintenance'), ('Tour & Travel', 'Tour & Travel'), ('Rent / Room Rent', 'Rent / Room Rent'), ('Electricity & Gas', 'Electricity & Gas'), ('Internet & WiFi', 'Internet & WiFi'), ('Mobile Recharge', 'Mobile Recharge'), ('bKash / Nagad', 'bKash / Nagad'), ('Clothing & Tailoring', 'Clothing & Tailoring'), ('Personal Care', 'Personal Care'), ('Medicine & Health', 'Medicine & Health'), ('Gym & Sports', 'Gym & Sports'), ('Entertainment & Subscriptions', 'Entertainment & Subscriptions'), ('Gift', 'Gift'), ('Donation', 'Donation'), ('Debt Repayment', 'Debt Repayment'), ('Tech & Gadgets', 'Tech & Gadgets'), ('Savings & Investment', 'Savings & Investment'), ('Miscellaneous / Others', 'Miscellaneous / Others')], default='Miscellaneous / Others', max_length=100, verbose_name='ক্যাটাগরি'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Tuition & Fees', 'Tuition & Fees'), ('Books & Notes', 'Books & Notes'), ('Stationery', 'Stationery'), ('Courses & Training', 'Courses & Training'), ('Mess / Hall Bill', 'Mess / Hall Bill'), ('Restaurants & Fast Food', 'Restaurants & Fast Food'), ('Tea & Snacks', 'Tea & Snacks'), ('Groceries', 'Groceries'), ('Bus / Local Transport', 'Bus / Local Transport'), ('Rickshaw & CNG', 'Rickshaw & CNG'), ('Bike Fuel / Maintenance', 'Bike Fuel / Maintenance'), ('Tour & Travel', 'Tour & Travel'), ('Rent / Room Rent', 'Rent / Room Rent'), ('Electricity & Gas', 'Electricity & Gas'), ('Internet & WiFi', 'Internet & WiFi'), ('Mobile Recharge', 'Mobile Recharge'), ('bKash / Nagad', 'bKash / Nagad'), ('Clothing & Tailoring', 'Clothing & Tailoring'), ('Personal Care', 'Personal Care'), ('Medicine & Health', 'Medicine & Health'), ('Gym & Sports', 'Gym & Sports'), ('Entertainment & Subscriptions', 'Entertainment & Subscriptions'), ('Gift', 'Gift'), ('Donation', 'Donation'), ('Debt Repayment', 'Debt Repayment'), ('Tech & Gadgets', 'Tech & Gadgets'), ('Savings & Investment', 'Savings & Investment'), ('Miscellaneous / Others', 'Miscellaneous / Others')], max_length=100, verbose_name='ক্যাটাগরি'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
